changelog:
  categories:
    - title: 🌲 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🪓 Refactoring
      labels:
        - refactor
    - title: 📝 Documentation
      labels:
        - documentation
    - title: 🚜 Dependencies
      labels:
        - dependencies
    - title: 👒 Chores
      labels:
        - "*"
