name: Create Release
on: [workflow_dispatch]
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Get previous tag
        id: pre_tag
        run: |
          pre_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "pre_tag=$pre_tag" >> $GITHUB_OUTPUT
      - name: Generate release tag
        id: release_tag
        run: |
          today=$(date +'%Y.%m.%d')
          pre_release_date=$(echo ${{ steps.pre_tag.outputs.pre_tag }} | awk -F'-' '{print $1}')
          pre_release_count=$(echo ${{ steps.pre_tag.outputs.pre_tag }} | awk -F'-' '{print $2}')
          
          if [[ ! $pre_release_date = $today ]]; then
            echo "init count"
            pre_release_count=0
          fi
          
          release_tag="$today-$(($pre_release_count + 1))"
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
      - name: Create Release
        run: |
          gh release create \
            ${{ steps.release_tag.outputs.release_tag }} \
            --generate-notes
            --draft
