name: Create Release
on: [workflow_dispatch]
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"
    steps:
      - name: Create Release
        run: |
          pre_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')

          today=$(date +'%Y.%m.%d')
          pre_release_date=$(pre_tag | awk -F'-' '{print $1}')
          pre_release_count=$(pre_tag | awk -F'-' '{print $2}')
          
          if [[ ! $pre_release_date = $today ]]; then
            echo "init count"
            pre_release_count=0
          fi
          
          release_tag="$today-$(($pre_release_count + 1))"

          gh release create release_tag --generate-notes --draft
